# Copied from https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml

name: generate snake animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "30 */1 * * *" 

  # allows to manually run the job at any time
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: ColoursofOSINT/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # push the content of dist to the snake branch
      # the content will be available at https://raw.githubusercontent.com/ColoursofOSINT/ColoursofOSINT/snake/dist/*.svg
      - name: push github-contribution-grid-snake.svg to the snake branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
